/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FunlinerYachtRouteImport } from './routes/funliner-yacht'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RentalsYachtRouteImport } from './routes/rentals/yacht'
import { Route as RentalsVillaGoaRouteImport } from './routes/rentals/villa-goa'
import { Route as RentalsSunset42RouteImport } from './routes/rentals/sunset-42'
import { Route as RentalsSeaRayRouteImport } from './routes/rentals/sea-ray'
import { Route as RentalsPrestige17RouteImport } from './routes/rentals/prestige-17'
import { Route as RentalsMajesticBaysRouteImport } from './routes/rentals/majestic-bays'
import { Route as RentalsLuxuryYacht12RouteImport } from './routes/rentals/luxury-yacht-12'
import { Route as RentalsFunlinerYachtRouteImport } from './routes/rentals/funliner-yacht'
import { Route as RentalsCatamaranAcRouteImport } from './routes/rentals/catamaran-ac'
import { Route as RentalsCarRentalGoaRouteImport } from './routes/rentals/car-rental-goa'
import { Route as RentalsAquamarineRouteImport } from './routes/rentals/aquamarine'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FunlinerYachtRoute = FunlinerYachtRouteImport.update({
  id: '/funliner-yacht',
  path: '/funliner-yacht',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsYachtRoute = RentalsYachtRouteImport.update({
  id: '/rentals/yacht',
  path: '/rentals/yacht',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsVillaGoaRoute = RentalsVillaGoaRouteImport.update({
  id: '/rentals/villa-goa',
  path: '/rentals/villa-goa',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsSunset42Route = RentalsSunset42RouteImport.update({
  id: '/rentals/sunset-42',
  path: '/rentals/sunset-42',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsSeaRayRoute = RentalsSeaRayRouteImport.update({
  id: '/rentals/sea-ray',
  path: '/rentals/sea-ray',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsPrestige17Route = RentalsPrestige17RouteImport.update({
  id: '/rentals/prestige-17',
  path: '/rentals/prestige-17',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsMajesticBaysRoute = RentalsMajesticBaysRouteImport.update({
  id: '/rentals/majestic-bays',
  path: '/rentals/majestic-bays',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsLuxuryYacht12Route = RentalsLuxuryYacht12RouteImport.update({
  id: '/rentals/luxury-yacht-12',
  path: '/rentals/luxury-yacht-12',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsFunlinerYachtRoute = RentalsFunlinerYachtRouteImport.update({
  id: '/rentals/funliner-yacht',
  path: '/rentals/funliner-yacht',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsCatamaranAcRoute = RentalsCatamaranAcRouteImport.update({
  id: '/rentals/catamaran-ac',
  path: '/rentals/catamaran-ac',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsCarRentalGoaRoute = RentalsCarRentalGoaRouteImport.update({
  id: '/rentals/car-rental-goa',
  path: '/rentals/car-rental-goa',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsAquamarineRoute = RentalsAquamarineRouteImport.update({
  id: '/rentals/aquamarine',
  path: '/rentals/aquamarine',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/funliner-yacht': typeof FunlinerYachtRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/rentals/aquamarine': typeof RentalsAquamarineRoute
  '/rentals/car-rental-goa': typeof RentalsCarRentalGoaRoute
  '/rentals/catamaran-ac': typeof RentalsCatamaranAcRoute
  '/rentals/funliner-yacht': typeof RentalsFunlinerYachtRoute
  '/rentals/luxury-yacht-12': typeof RentalsLuxuryYacht12Route
  '/rentals/majestic-bays': typeof RentalsMajesticBaysRoute
  '/rentals/prestige-17': typeof RentalsPrestige17Route
  '/rentals/sea-ray': typeof RentalsSeaRayRoute
  '/rentals/sunset-42': typeof RentalsSunset42Route
  '/rentals/villa-goa': typeof RentalsVillaGoaRoute
  '/rentals/yacht': typeof RentalsYachtRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/funliner-yacht': typeof FunlinerYachtRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/rentals/aquamarine': typeof RentalsAquamarineRoute
  '/rentals/car-rental-goa': typeof RentalsCarRentalGoaRoute
  '/rentals/catamaran-ac': typeof RentalsCatamaranAcRoute
  '/rentals/funliner-yacht': typeof RentalsFunlinerYachtRoute
  '/rentals/luxury-yacht-12': typeof RentalsLuxuryYacht12Route
  '/rentals/majestic-bays': typeof RentalsMajesticBaysRoute
  '/rentals/prestige-17': typeof RentalsPrestige17Route
  '/rentals/sea-ray': typeof RentalsSeaRayRoute
  '/rentals/sunset-42': typeof RentalsSunset42Route
  '/rentals/villa-goa': typeof RentalsVillaGoaRoute
  '/rentals/yacht': typeof RentalsYachtRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/funliner-yacht': typeof FunlinerYachtRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/rentals/aquamarine': typeof RentalsAquamarineRoute
  '/rentals/car-rental-goa': typeof RentalsCarRentalGoaRoute
  '/rentals/catamaran-ac': typeof RentalsCatamaranAcRoute
  '/rentals/funliner-yacht': typeof RentalsFunlinerYachtRoute
  '/rentals/luxury-yacht-12': typeof RentalsLuxuryYacht12Route
  '/rentals/majestic-bays': typeof RentalsMajesticBaysRoute
  '/rentals/prestige-17': typeof RentalsPrestige17Route
  '/rentals/sea-ray': typeof RentalsSeaRayRoute
  '/rentals/sunset-42': typeof RentalsSunset42Route
  '/rentals/villa-goa': typeof RentalsVillaGoaRoute
  '/rentals/yacht': typeof RentalsYachtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/funliner-yacht'
    | '/gallery'
    | '/services'
    | '/rentals/aquamarine'
    | '/rentals/car-rental-goa'
    | '/rentals/catamaran-ac'
    | '/rentals/funliner-yacht'
    | '/rentals/luxury-yacht-12'
    | '/rentals/majestic-bays'
    | '/rentals/prestige-17'
    | '/rentals/sea-ray'
    | '/rentals/sunset-42'
    | '/rentals/villa-goa'
    | '/rentals/yacht'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/funliner-yacht'
    | '/gallery'
    | '/services'
    | '/rentals/aquamarine'
    | '/rentals/car-rental-goa'
    | '/rentals/catamaran-ac'
    | '/rentals/funliner-yacht'
    | '/rentals/luxury-yacht-12'
    | '/rentals/majestic-bays'
    | '/rentals/prestige-17'
    | '/rentals/sea-ray'
    | '/rentals/sunset-42'
    | '/rentals/villa-goa'
    | '/rentals/yacht'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/funliner-yacht'
    | '/gallery'
    | '/services'
    | '/rentals/aquamarine'
    | '/rentals/car-rental-goa'
    | '/rentals/catamaran-ac'
    | '/rentals/funliner-yacht'
    | '/rentals/luxury-yacht-12'
    | '/rentals/majestic-bays'
    | '/rentals/prestige-17'
    | '/rentals/sea-ray'
    | '/rentals/sunset-42'
    | '/rentals/villa-goa'
    | '/rentals/yacht'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FunlinerYachtRoute: typeof FunlinerYachtRoute
  GalleryRoute: typeof GalleryRoute
  ServicesRoute: typeof ServicesRoute
  RentalsAquamarineRoute: typeof RentalsAquamarineRoute
  RentalsCarRentalGoaRoute: typeof RentalsCarRentalGoaRoute
  RentalsCatamaranAcRoute: typeof RentalsCatamaranAcRoute
  RentalsFunlinerYachtRoute: typeof RentalsFunlinerYachtRoute
  RentalsLuxuryYacht12Route: typeof RentalsLuxuryYacht12Route
  RentalsMajesticBaysRoute: typeof RentalsMajesticBaysRoute
  RentalsPrestige17Route: typeof RentalsPrestige17Route
  RentalsSeaRayRoute: typeof RentalsSeaRayRoute
  RentalsSunset42Route: typeof RentalsSunset42Route
  RentalsVillaGoaRoute: typeof RentalsVillaGoaRoute
  RentalsYachtRoute: typeof RentalsYachtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funliner-yacht': {
      id: '/funliner-yacht'
      path: '/funliner-yacht'
      fullPath: '/funliner-yacht'
      preLoaderRoute: typeof FunlinerYachtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/yacht': {
      id: '/rentals/yacht'
      path: '/rentals/yacht'
      fullPath: '/rentals/yacht'
      preLoaderRoute: typeof RentalsYachtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/villa-goa': {
      id: '/rentals/villa-goa'
      path: '/rentals/villa-goa'
      fullPath: '/rentals/villa-goa'
      preLoaderRoute: typeof RentalsVillaGoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/sunset-42': {
      id: '/rentals/sunset-42'
      path: '/rentals/sunset-42'
      fullPath: '/rentals/sunset-42'
      preLoaderRoute: typeof RentalsSunset42RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/sea-ray': {
      id: '/rentals/sea-ray'
      path: '/rentals/sea-ray'
      fullPath: '/rentals/sea-ray'
      preLoaderRoute: typeof RentalsSeaRayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/prestige-17': {
      id: '/rentals/prestige-17'
      path: '/rentals/prestige-17'
      fullPath: '/rentals/prestige-17'
      preLoaderRoute: typeof RentalsPrestige17RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/majestic-bays': {
      id: '/rentals/majestic-bays'
      path: '/rentals/majestic-bays'
      fullPath: '/rentals/majestic-bays'
      preLoaderRoute: typeof RentalsMajesticBaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/luxury-yacht-12': {
      id: '/rentals/luxury-yacht-12'
      path: '/rentals/luxury-yacht-12'
      fullPath: '/rentals/luxury-yacht-12'
      preLoaderRoute: typeof RentalsLuxuryYacht12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/funliner-yacht': {
      id: '/rentals/funliner-yacht'
      path: '/rentals/funliner-yacht'
      fullPath: '/rentals/funliner-yacht'
      preLoaderRoute: typeof RentalsFunlinerYachtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/catamaran-ac': {
      id: '/rentals/catamaran-ac'
      path: '/rentals/catamaran-ac'
      fullPath: '/rentals/catamaran-ac'
      preLoaderRoute: typeof RentalsCatamaranAcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/car-rental-goa': {
      id: '/rentals/car-rental-goa'
      path: '/rentals/car-rental-goa'
      fullPath: '/rentals/car-rental-goa'
      preLoaderRoute: typeof RentalsCarRentalGoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/aquamarine': {
      id: '/rentals/aquamarine'
      path: '/rentals/aquamarine'
      fullPath: '/rentals/aquamarine'
      preLoaderRoute: typeof RentalsAquamarineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FunlinerYachtRoute: FunlinerYachtRoute,
  GalleryRoute: GalleryRoute,
  ServicesRoute: ServicesRoute,
  RentalsAquamarineRoute: RentalsAquamarineRoute,
  RentalsCarRentalGoaRoute: RentalsCarRentalGoaRoute,
  RentalsCatamaranAcRoute: RentalsCatamaranAcRoute,
  RentalsFunlinerYachtRoute: RentalsFunlinerYachtRoute,
  RentalsLuxuryYacht12Route: RentalsLuxuryYacht12Route,
  RentalsMajesticBaysRoute: RentalsMajesticBaysRoute,
  RentalsPrestige17Route: RentalsPrestige17Route,
  RentalsSeaRayRoute: RentalsSeaRayRoute,
  RentalsSunset42Route: RentalsSunset42Route,
  RentalsVillaGoaRoute: RentalsVillaGoaRoute,
  RentalsYachtRoute: RentalsYachtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
